# Generated by Django 3.2 on 2021-04-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
