# Generated by Django 3.2 on 2021-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0002_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invite', 'invite'), ('friends', 'friends'), ('blocked', 'blocked'), ('declined', 'declined')], max_length=50, null=True)),
            ],
        ),
    ]
