# Generated by Django 3.2 on 2021-04-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0003_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='Workout.customer'),
        ),
        migrations.AddField(
            model_name='relations',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='Workout.customer'),
        ),
    ]
