# Generated by Django 3.2 on 2021-04-25 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0004_auto_20210424_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='status',
            field=models.CharField(choices=[('invite', 'invite'), ('friends', 'friends'), ('blocked', 'blocked'), ('declined', 'declined'), ('banned', 'banned')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='dialogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiverText', to='Workout.customer')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senderText', to='Workout.customer')),
            ],
        ),
    ]
