# Generated by Django 3.2 on 2021-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0005_auto_20210426_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogues',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
