# Generated by Django 3.2 on 2021-04-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0006_dialogues_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
