# Generated by Django 3.2 on 2021-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0007_delete_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='level',
            field=models.CharField(choices=[('PROFESSIONAL', 'PROFESSIONAL'), ('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE')], max_length=50, null=True),
        ),
    ]
